name: task_flow_web
description:
  Privacy Policy website for Task Flow
version: 1.0.0

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  web: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^5.0.0
